# Generated by Django 5.0.1 on 2024-02-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='cессия для оплаты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.course', verbose_name='курс'),
        ),
    ]
