# Generated by Django 5.0.1 on 2024-02-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_payment_is_successful_payment_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='cтоимость курса'),
        ),
    ]
